/**
 * Fallback PDF Export Utility - Simple Version
 * Creates a basic PDF document from the generated world data
 */
class SimplePDFExporter {
  constructor() {
    this.worldData = null;
  }

  /**
   * Export world data as a formatted text file (fallback)
   */
  async exportWorldAsText(worldData) {
    if (!worldData) {
      throw new Error('No world data to export');
    }

    const {
      worldNarrative,
      gameBookIdeas,
      customizationOptions,
      characterConcepts,
      conceptualMaps,
      userIdea,
      worldType
    } = worldData;

    let content = '';
    content += '=====================================\n';
    content += '       LUMINA OZ GAME DEV\n';
    content += '     World Building Tool Export\n';
    content += '=====================================\n\n';
    
    content += `World Type: ${worldType}\n`;
    content += `Original Idea: "${userIdea}"\n\n`;
    
    if (worldNarrative) {
      content += '--- WORLD NARRATIVE ---\n';
      content += worldNarrative + '\n\n';
    }
    
    if (characterConcepts && characterConcepts.length > 0) {
      content += '--- CHARACTER CONCEPTS ---\n';
      characterConcepts.forEach((char, index) => {
        content += `${index + 1}. ${char.name} (${char.role})\n`;
        content += `   ${char.description}\n\n`;
      });
    }
    
    if (gameBookIdeas && gameBookIdeas.length > 0) {
      content += '--- GAME & BOOK IDEAS ---\n';
      gameBookIdeas.forEach((idea, index) => {
        content += `${index + 1}. ${idea.title}\n`;
        content += `   ${idea.synopsis}\n\n`;
      });
    }
    
    if (customizationOptions && customizationOptions.length > 0) {
      content += '--- CUSTOMIZATION OPTIONS ---\n';
      customizationOptions.forEach((option, index) => {
        content += `${index + 1}. ${option.title}\n`;
        content += `   ${option.description}\n\n`;
      });
    }
    
    if (conceptualMaps) {
      content += '--- CONCEPTUAL MAPS & REGIONS ---\n';
      content += conceptualMaps + '\n\n';
    }
    
    content += '=====================================\n';
    content += 'Generated by Lumina Oz Game Dev\n';
    content += 'World Building Tool\n';
    content += `Export Date: ${new Date().toLocaleDateString()}\n`;
    content += '=====================================\n';

    // Create and download the text file
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    
    const sanitizedWorldType = worldType.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    const timestamp = new Date().toISOString().slice(0, 10);
    const filename = `world_${sanitizedWorldType}_${timestamp}.txt`;
    
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    return filename;
  }
}

export default SimplePDFExporter;